<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.seth-yang</groupId>
        <artifactId>dreamwork-parent</artifactId>
        <version>1.0.0</version>
        <relativePath />
    </parent>

    <artifactId>java-wrapper-for-sherpa-onnx</artifactId>
    <name>java-wrapper-for-sherpa-onnx</name>
    <version>1.0.0</version>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <scm>
        <connection>scm:git:https://github.com/seth-yang/java-wrapper-for-sherpa-onnx</connection>
        <developerConnection>scm:git:git@hithub.com:seth-yang/ok-http-wrapper</developerConnection>
        <url>https://github.com/seth-yang/java-wrapper-for-sherpa-onnx</url>
        <tag>HEAD</tag>
    </scm>

    <dependencies>
        <dependency>
            <groupId>io.github.seth-yang</groupId>
            <artifactId>dreamwork-base</artifactId>
            <version>3.1.8</version>
            <exclusions>
                <exclusion>
                    <groupId>com.google.code.gson</groupId>
                    <artifactId>gson</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.k2fsa.sherpa.onnx</groupId>
            <artifactId>sherpa-onnx-jvm</artifactId>
            <version>1.13.8</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.22.1</version>
        </dependency>
    </dependencies>
</project>